<Project>
  <ItemGroup Condition="'$(PublishAot)' == 'true' AND '$(RuntimeIdentifier)' != ''">
  
    <NativeLibrary Include="$(MSBuildThisFileDirectory)..\static\$(RuntimeIdentifier)\libstbvorbis.lib"
                   Condition="$(RuntimeIdentifier.Contains('win'))" />

    <NativeLibrary Include="$(MSBuildThisFileDirectory)..\static\$(RuntimeIdentifier)\libstbvorbis.a"
                   Condition="$(RuntimeIdentifier.Contains('linux')) OR $(RuntimeIdentifier.Contains('osx'))" />

    <DirectPInvoke Include="libstbvorbis" />
  </ItemGroup>

  <Target Name="RemoveDynamicLibrariesWhenStaticallyLinkingStbVorbis"
          AfterTargets="ComputeFilesToPublish"
          Condition="'$(PublishAot)' == 'true' AND '$(RuntimeIdentifier)' != ''">
          
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" 
                             Condition="
                     '%(Filename)%(Extension)' == 'libstbvorbis.dll' OR
                     '%(Filename)%(Extension)' == 'libstbvorbis.so' OR
                     '%(Filename)%(Extension)' == 'libstbvorbis.dylib'" />
    </ItemGroup>
  </Target>
</Project>
