name: Compile Native Libraries && NuGet Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [linux-x64, linux-x86]
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive
    
    - name: Compile for ${{ matrix.target }}
      shell: pwsh
      run: |
        pwsh build-prep.ps1
        pwsh build-target.ps1 ${{ matrix.target }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-build
        path: src/
        
  build-linux-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        target: [linux-arm, linux-arm64]
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Compile for ${{ matrix.target }}
        shell: pwsh
        run: |
          pwsh build-prep.ps1
          pwsh build-target.ps1 ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}-build
          path: src/

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [osx-arm64, osx-x64]
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive
    
    - name: Compile for ${{ matrix.target }}
      shell: pwsh
      run: |
        pwsh build-prep.ps1
        pwsh build-target.ps1 ${{ matrix.target }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-build
        path: src/

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win-x64, win-x86]
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive
    
    - name: Compile for ${{ matrix.target }}
      shell: pwsh
      run: |
        pwsh build-prep.ps1
        pwsh build-target.ps1 ${{ matrix.target }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-build
        path: src/

  build-windows-arm:
    runs-on: windows-11-arm
    strategy:
      matrix:
        target: [win-arm64]
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive
    
    - name: Compile for ${{ matrix.target }}
      shell: pwsh
      run: |
        pwsh build-prep.ps1
        pwsh build-target.ps1 ${{ matrix.target }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.target }}-build
        path: src/

  push-package:
    needs: [build-linux, build-linux-arm, build-macos, build-windows, build-windows-arm]
    runs-on: ubuntu-latest
    permissions:
      contents: write # for the GitHub release upload
      id-token: write # for NuGet's Trusted Publishing
    
    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v7
      with:
        submodules: recursive
      
    - name: Download all artifacts
      uses: actions/download-artifact@v8
      with:
        path: src
        pattern: '*-build'
        merge-multiple: true
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Push package
      shell: pwsh
      run: |
        pwsh push-package.ps1
      env:
        GH_TOKEN: ${{ github.token }}
        NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
        VERSION: ${{ github.event.inputs.version }}
